CREATE TABLE [dbo].[BlitzChecksToSkip](
	[ServerName] [nvarchar](128) NULL,
	[DatabaseName] [nvarchar](128) NULL,
	[CheckID] [int] NULL, 
    [Comment] NVARCHAR(250) NULL, 
)
GO
CREATE UNIQUE CLUSTERED INDEX [PK_BlitzChecksToSkip] ON [dbo].[BlitzChecksToSkip]
(
	[ServerName] ASC,
	[DatabaseName] ASC,
	[CheckID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO