CREATE TABLE [dbo].[BlitzServerMapping](
	[ServerName] NVARCHAR(50) NOT NULL,
	[Alias] NVARCHAR(50) NULL, 
    [SortOrder] INT NULL
)
GO
ALTER TABLE [dbo].[BlitzServerMapping] ADD  CONSTRAINT [PK_BlitzServerMapping] PRIMARY KEY CLUSTERED 
(
	[ServerName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO